---
format: html
execute:
  echo: false
  warning: false
  message: false
freeze: true
---

```{r setup}
library(tidyr)
library(dplyr)
library(stringr)
library(tidytext)
library(googlesheets4)
library(wordcloud2)

# fetch data
url <- "https://docs.google.com/spreadsheets/d/1LE3XGIIMX0rCvGA_a6taXD4X9FWoT_pN7NlbjNMLc_E/edit?usp=sharing"
ppts <- read_sheet(url)
```

```{r}
keywords <- ppts |>
    select(id, contains("keywords"))
colnames(keywords) <- c("id", "responsible", "irresponsible")
# split into keywords delimited by commas (up to 3 for each responsible/irresponsible)
keywords <- keywords |>
  pivot_longer(cols = c(responsible, irresponsible), names_to = "type", values_to = "keywords") |>
  separate_longer_delim(keywords, delim = ",") |>
  unnest_tokens(output = keyword, input = keywords) |>
  anti_join(get_stopwords("en"), by = c("keyword" = "word")) |>
  mutate(keyword = ifelse(keyword=="na", NA, keyword))
```

```{r}
# arrange
keywords <- keywords |>
group_by(type, keyword) |>
count() |>
mutate(color = if_else(type == "responsible", "#0173B2", "#DE8F05")) |> 
  drop_na()

# prepare data for wordcloud2
wc_data <- keywords |>
select(keyword, n) |>
as.data.frame()

# create colour vector in same order as wc_data
word_colors <- keywords$color[match(wc_data$keyword, keywords$keyword)]
```


```{r wordcloud}
irrespo <- filter(keywords, type == "irresponsible") |> 
  drop_na()


```

`r nrow(ppts)` participants, contributing up to 3 keywords to describe responsible/irresponsible modelling^[_Using up to 3 keywords, what does "responsible"/"irresponsible" modelling look like for you?_]. Word size represents frequency; coloured blue for responsible, orange for irresponsible.
