---
title: "24 March 2026"
---

*Draft schedule*

This workshop aims to encourage participant reflection, discussion, and co-design. 
Each session builds from panels and a variety of formats for effective and fun group discussion[^1].

[^1]: Workshop design motivated by a [*What / So What / Now What*](https://www.liberatingstructures.com/9-what-so-what-now-what-w/) structure, and heavily borrows from the principles of LS groupwork.

+--------------+---------------------------------------------------------------+
| Time         | Session                                                       |
+==============+===============================================================+
| 10:00        | Welcome activity                                              |
|              |                                                               |
|              | > Participants: Nominating role models                        |
+--------------+---------------------------------------------------------------+
| 10:15        | Introduction & aims                                           |
|              |                                                               |
|              | > Welcome: Katharine Sherratt, Sebastian Funk, Erica Thompson |
+--------------+---------------------------------------------------------------+
|              | **Session A: Scientific responsibility**                      |
+--------------+---------------------------------------------------------------+
| 10:30        | Opening: Modelling & scientific responsibility                |
|              |                                                               |
|              | > Speaker: Sebastian Funk                                     |
+--------------+---------------------------------------------------------------+
| 10:40        | Evaluation across epidemiological contexts                    |
|              |                                                               |
|              | > Panel: Matt Keeling, Kaitlyn Johnson                        |
+--------------+---------------------------------------------------------------+
| 11:10        | Implications for scientific responsibility                    |
|              |                                                               |
|              | > Participants: Nested group discussion                       |
+--------------+---------------------------------------------------------------+
| 11:30        | *Coffee break*                                                |
+--------------+---------------------------------------------------------------+
| 11:45        | Training scientifically responsible modellers                 |
|              |                                                               |
|              | > Participants: Small group co-design                         |
+--------------+---------------------------------------------------------------+
| 12:30        | *Lunch*                                                       |
+--------------+---------------------------------------------------------------+
|              | **Session B: Social responsibility**                          |
+--------------+---------------------------------------------------------------+
| 13:30        | Opening: Modelling & social responsibility                    |
|              |                                                               |
|              | > Speaker: Erica Thompson                                     |
+--------------+---------------------------------------------------------------+
| 13:40        | Evaluation across public health contexts                      |
|              |                                                               |
|              | > Panel: Graham Medley, Elinor Godfrey                        |
+--------------+---------------------------------------------------------------+
| 14:10        | Implications for social responsibility                        |
|              |                                                               |
|              | > Participants: Nested group discussion                       |
+--------------+---------------------------------------------------------------+
| 14:30        | *Fresh air break*                                             |
+--------------+---------------------------------------------------------------+
| 15:00        | Training socially responsible modellers                       |
|              |                                                               |
|              | > Participants: Small group co-design                         |
+--------------+---------------------------------------------------------------+
| 15:45        | Gallery of co-designed training materials                     |
+--------------+---------------------------------------------------------------+
|              | **Implementation**                                            |
+--------------+---------------------------------------------------------------+
| 16:00        | Crowd sourcing: big priorities and smallest next steps        |
|              |                                                               |
|              | > Participants: Rapid rating exercise                         |
+--------------+---------------------------------------------------------------+
| 16:30        | Close                                                         |
+--------------+---------------------------------------------------------------+