---
title: "How do we evaluate modelling work, and what does that imply about modelling responsibly?"
---

::: {.callout-note .column-margin}
## Key details

-   24 March 2026, 10.00–16.30
-   LSHTM, Keppel St, London WC1E 7HT
-   30 participants across academia and public health

<button>[Register](register.qmd)</button>

:::

::: panel-tabset
## Overview

We're inviting participants to join a one day workshop on evaluation and responsibility in infectious disease modelling. Through the day, we'll:

-   compare perspectives on evaluation in epidemiological and public health contexts
-   collaboratively map out what this means for professional norms, values, and responsibilities
-   experiment with what this looks like in practice by co-designing training material for modellers

We intend to directly support participants by building up practical ideas, resources, and relationships. While we anticipate a UK focus, we welcome contributions from any context. We encourage participants from all career experiences and interests to join.

<button>[Register](register.qmd)</button>

## Agenda

*Draft schedule*

This workshop aims to encourage participant reflection, discussion, and co-design. 
Each session builds from panels and a variety of formats for effective and fun group discussion[^1].

[^1]: Workshop design motivated by principles of [structured groupwork](https://www.liberatingstructures.com/).

+--------------+---------------------------------------------------------------+
| 09.45        | Arrival                                                       |
+--------------+---------------------------------------------------------------+
| 10:00        | Welcome activity                                              |
|              |                                                               |
|              | > Participants: Nominating role models                        |
+--------------+---------------------------------------------------------------+
| 10:15        | Introduction & aims                                           |
|              |                                                               |
|              | > Welcome: Katharine Sherratt, Sebastian Funk, Erica Thompson |
+--------------+---------------------------------------------------------------+
|              | **Session A: Scientific responsibility**                      |
+--------------+---------------------------------------------------------------+
| 10:30        | Opening: Modelling & scientific responsibility                |
|              |                                                               |
|              | > Speaker: Sebastian Funk                                     |
+--------------+---------------------------------------------------------------+
| 10:40        | Panel: Evaluation across epidemiological contexts             |
|              |                                                               |
|              | > Matt Keeling (Uni. Warwick), Kaitlyn Johnson (LSHTM), TBC |
+--------------+---------------------------------------------------------------+
| 11:10        | Implications for scientific responsibility                    |
|              |                                                               |
|              | > Participants: Nested group discussion                       |
+--------------+---------------------------------------------------------------+
| 11:30        | *Coffee break*                                                |
+--------------+---------------------------------------------------------------+
| 11:45        | Training scientifically responsible modellers                 |
|              |                                                               |
|              | > Participants: Small group co-design                         |
+--------------+---------------------------------------------------------------+
| 12:30        | *Lunch*                                                       |
+--------------+---------------------------------------------------------------+
|              | **Session B: Social responsibility**                          |
+--------------+---------------------------------------------------------------+
| 13:30        | Opening: Modelling & social responsibility                    |
|              |                                                               |
|              | > Speaker: Erica Thompson (UCL)                               |
+--------------+---------------------------------------------------------------+
| 13:40        | Panel: Evaluation across public health contexts               |
|              |                                                               |
|              | > Graham Medley (LSHTM), Juan Vesga (UKHSA), TBC              |
+--------------+---------------------------------------------------------------+
| 14:10        | Implications for social responsibility                        |
|              |                                                               |
|              | > Participants: Nested group discussion                       |
+--------------+---------------------------------------------------------------+
| 14:30        | *Fresh air break*                                             |
+--------------+---------------------------------------------------------------+
| 15:00        | Training socially responsible modellers                       |
|              |                                                               |
|              | > Participants: Small group co-design                         |
+--------------+---------------------------------------------------------------+
| 15:45        | Gallery of co-designed training materials                     |
+--------------+---------------------------------------------------------------+
|              | **Implementation**                                            |
+--------------+---------------------------------------------------------------+
| 16:00        | Crowd sourcing: big priorities and smallest next steps        |
|              |                                                               |
|              | > Participants: Rapid rating exercise                         |
+--------------+---------------------------------------------------------------+
| 16:30        | Close                                                         |
+--------------+---------------------------------------------------------------+

## Join

This event is open to all, and we welcome anyone to join. 
Just let us know you're interested and we'll share logistics for the day.
For more information, contact: [Kath Sherratt](mailto:katharine.sherratt@lshtm.ac.uk)

<button>[Register](register.qmd)</button>

:::

------------------------------------------------------------------------

Organised by Kath Sherratt (LSHTM), Seb Funk (LSHTM), and Erica Thompson (UCL), and supported by LSHTM CMMID