---
title: "Participate"
---

We encourage participants to join from any background and experience. 

Registration for the workshop is open until 13 March.

We have a limit on the number of participant places so that we can best support group work.
We are likely to be oversubscribed and will operate a waitlist after this point.

We will be in touch by 17 March to confirm places.
Please [let us know](register_confirmation.html) as soon as possible if you can no longer attend.

::: {.callout-note collapse="true"}
## Participant support

There is no cost to attend.

We will provide lunch and refreshments.
We have some funds available to support UK travel, and can make accessibility adjustments wherever possible.

Please email Kath at [katharine.sherratt@lshtm.ac.uk](mailto:katharine.sherratt@lshtm.ac.uk) for more information and support with travel or accessibility.

We are unable to provide recordings of the workshop. All workshop materials will be available on this website.
:::


<iframe style="border:none;width:100%;" id="contact-form-m3dino" src="https://opnform.com/forms/contact-form-m3dino"></iframe><script type="text/javascript" onload="initEmbed('contact-form-m3dino', { autoResize: true })" src="https://opnform.com/widgets/iframe.min.js"></script>

<button><a href="workshop_invite.ics" download>Download calendar event</a></button>